steps:
  # 1. Docker Build: Image banana (Repo ka naam yahan use ho raha hai)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/time-app-repo-ecs/time-app-image', '.']

  # 2. Docker Push: Image ko Registry mein bhejna
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/time-app-repo-ecs/time-app-image']

  # 3. Deploy: Cloud Run (ECS Service ki tarah) par deploy karna
  # 3. Deploy: Cloud Run par deploy karna
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'time-app-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/time-app-repo-ecs/time-app-image'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '80'  # <--- Ye line lazmi add karein
      - '--allow-unauthenticated'

# Logs ka error khatam karne ke liye
options:
  logging: CLOUD_LOGGING_ONLY
